#!/bin/python3

import argparse

parser = argparse.ArgumentParser(
    description="Calculo da taxa efetiva",
    epilog="FORMULA: ( (1 + (i/100) / q)**q-1 ) * 100",
)

parser.add_argument("I", type=float, help="Taxa")
parser.add_argument("Q", type=float, help="Periodo")

parser.add_argument("-n", type=int, default=4, help="Número de casas decimais")

args = parser.parse_args()

print(f"{ (1+(args.I/100)/args.Q)**args.Q-1 :.{args.n}%}")
